"Testing for Multiple Items - Restructuring Main" in chapter 16.
> The test is failing because the Sniper is not sending a Join message for the
> second auction. We must change `Main` to interpret the additional arguments.
>
> To add multiple items, we need to distinguish between the code that
> establishes a connection to the auction server and the code that joins an
> auction. We start by holding on to connection so we can reuse it with
> multiple chats; the result is not very object-oriented but we want to wait
> and see how the structure develops. We also change
> `@not_to_be_garbage_collected` from a single value to a collection.
>
> We loop through each of the items that we’ve been given.
>
> This is ugly, but it does show us a separation between the code for the
> single connection and multiple auctions. We have a hunch it'll be cleaned up
> before long.
>
> The end-to-end test now shows us that display cannot handle the additional
> item we’ve just fed in. The table model is still hard-coded to support one
> row, so one of the items will be ignored:

      1) Error:
    test_0004_bids_for_multiple_items(AuctionsniperSpec):
    NativeException: java.lang.AssertionError:
    Tried to look for...
        exactly 1 JTable (with name "Snipers Table")
        in exactly 1 JFrame (with name "Auction Sniper Main" and showing on screen)
        in all top level windows
    and check that it is table with row with cells <label with text "item-65432">, <label with text "521">, <label with text "521">, <label with text "winning">
    but...
        all top level windows
        contained 1 JFrame (with name "Auction Sniper Main" and showing on screen)
        contained 1 JTable (with name "Snipers Table")
       it is not table with row with cells <label with text "item-65432">, <label with text "521">, <label with text "521">, <label with text "winning">
        because
          in row 0: component 0 text was "item-54321"

> Incidentally, this result is a nice example of why we needed to be aware of
> timing in end-to-end tests. This test might fail when looking for `@auction`
> or `@auction2`. The asynchrony of the system means that we can't tell which
> will arrive first.

Notes:

* I chose to assign `@not_to_be_garbage_collected` in the `#initialize` method.
  Presumably it's initialized in a field declaration in the Java code.

* I used a slightly more Ruby-ish way of looping through the item ID arguments.

* I had to make `Main#disconnect_when_ui_closes` public since it's now being
  called on the instance from a class method "outside" the instance.