"Final Polish - A Test for Column Titles" in chapter 15.
> To make the user interface presentable, we need to fill in the column titles
> which, as we saw in Figure 15.3, are still missing. This isn’t difficult,
> since most of the implementation is built into Swing’s `TableModel`. As
> always, we start with the acceptance test. We add extra validation to
> `AuctionSniperDriver` that will be called by the method in
> `ApplicationRunner` that starts up the Sniper. For good measure, we throw
> in a check for the application’s displayed title.
>
> The test fails:

      1) Error:
    test_0001_joins_auction_until_auction_closes(AuctionsniperSpec):
    NativeException: java.lang.AssertionError:
    Tried to look for...
        exactly 1 JTableHeader ()
        in exactly 1 JFrame (with name "Auction Sniper Main" and showing on screen)
        in all top level windows
    and check that it is table with headers with cells <label with text "Item">, <label with text "Last Price">, <label with text "Last Bid">, <label with text "State">
    but...
        all top level windows
        contained 1 JFrame (with name "Auction Sniper Main" and showing on screen)
        contained 1 JTableHeader ()
       it is not table with headers with cells <label with text "Item">, <label with text "Last Price">, <label with text "Last Bid">, <label with text "State">
        because component 0 text was "A"

Note that I had to pass `JTableHeader.java_class` into the `JTableHeaderDriver`
constructor instead of `JTableHeader.class` to avoid the following exception:

    NativeException: java.lang.IllegalStateException: probe failed