Fixed first end-to-end test in "Sniper Has More to Say" in chapter 14.
Now the end-to-end test is failing, because the sniper thinks it has
lost when it has actually won :-

    NativeException: java.lang.AssertionError:
    Tried to look for...
        exactly 1 JLabel (with name "sniper status")
        in exactly 1 JFrame (with name "Auction Sniper Main" and showing
on screen)
        in all top level windows
    and check that its label text is "won"
    but...
        all top level windows
        contained 1 JFrame (with name "Auction Sniper Main" and showing
on screen)
        contained 1 JLabel (with name "sniper status")
        label text was "lost"
        com/objogate/wl/PollingProber.java:38:in `check'
        com/objogate/wl/swing/driver/ComponentDriver.java:74:in `check'
        com/objogate/wl/swing/driver/ComponentDriver.java:142:in `has'
        com/objogate/wl/swing/driver/JLabelDriver.java:30:in `hasText'
        test/end-to-end/auction_sniper_driver.rb:25:in
`shows_sniper_status'
        test/end-to-end/application_runner.rb:40:in
`shows_sniper_has_won_auction'
        test/end-to-end/auction_sniper_end_to_end_test.rb:47:in
`test_0003_wins_an_auction_by_bidding_higher'