"A Surprise Failure" in "A Test for Bidding" in chapter 12.
    org.jivesoftware.smack.XMPPException: conflict(409)
    org/jivesoftware/smack/SASLAuthentication.java:434:in
    `bindResourceAndEstablishSession'
    org/jivesoftware/smack/SASLAuthentication.java:331:in `authenticate'
    org/jivesoftware/smack/XMPPConnection.java:395:in `login'
    /Users/jamesmead/Code/freerange/gosling/app/main.rb:47:in `connection'
    /Users/jamesmead/Code/freerange/gosling/app/main.rb:31:in `main'
    /Users/jamesmead/Code/freerange/gosling/test/end-to-end/application_runner.rb:15:in
    `start_bidding_in'