"What If It Doesn't Work?", chapter 19.
> Our product people are concerned that Southabee's On-Line has a reputation
> for occasionally failing and sending incorrectly structured messages, so they
> want us to show that we can cope. It turns out that the system we talk to is
> actually an aggregator for multiple auction feeds, so the failure of an
> individual auction does not imply that the whole system is unsafe. Our policy
> will be that when we receive a message that we cannot interpret, we will mark
> that auction as Failed and ignore any further updates, since it means we can
> no longer be sure what's happening. Once an auction has failed, we make no
> attempt to recover.
>
> In practice, reporting a message failure means that we flush the price and
> bid values, and show the status as Failed for the offending item. We also
> record the event somewhere so that we can deal with it later. We could make
> the display of the failure more obvious, for example by coloring the row, but
> we'll keep this version simple and leave any extras as an exercise for the
> reader.
>
> The end-to-end test shows that a working Sniper receives a bad message,
> displays and records the failure, and then ignores further updates from this
> auction:

      1) Error:
    test_0006_sniper_reports_invalid_auction_message_and_stops_responding_to_events(AuctionsniperSpec):
    NativeException: java.lang.AssertionError:
    Tried to look for...
        exactly 1 JTable (with name "Snipers Table")
        in exactly 1 JFrame (with name "Auction Sniper Main" and showing on screen)
        in all top level windows
    and check that it is table with row with cells <label with text "item-54321">, <label with text "0">, <label with text "0">, <label with text "failed">
    but...
        all top level windows
        contained 1 JFrame (with name "Auction Sniper Main" and showing on screen)
        contained 1 JTable (with name "Snipers Table")
       it is not table with row with cells <label with text "item-54321">, <label with text "0">, <label with text "0">, <label with text "failed">
        because
          in row 0: component 1 text was "500"
          in row 1: component 0 text was "item-65432"

> It shows that there are two rows in the table: the second is for the other
> auction, and the first is showing that the current price is 500 when it
> should have been flushed to 0. This failure is our marker for what we need to
> build next.