"Testing for Multiple Items - A Diversion" in chapter 16.
> Fixing the Failure Message.
>
> We first saw this cryptic failure message in Chapter 11. It wasn't so bad
> then because it could only occur in one place and there wasn't much code
> to test anyway. Now it's more annoying because we have to find this method
> and figure out what we’re missing. We’d like to combine these two
> assertions and provide a more meaningful failure. We could write a custom
> matcher for the message body but, given that the structure of `Message` is
> not going to change soon, we can use a `PropertyMatcher` which produces
> this more helpful failure report:

      1) Error:
    test_0004_bids_for_multiple_items(AuctionsniperSpec):
    NativeException: java.lang.AssertionError:
    Expected: hasProperty("body", "SQLVersion: 1.1; Command: JOIN;")
         but: was null