"First a Failing Test" in "The Sniper Wins the Auction" in chapter 14.
I also tidied up the names of the end-to-end tests given that we're
using the MiniTest::Spec, we might as well make the test as readable as
possible.

Note that the newly added end-to-end test is currently failing, because
we are in the middle of implementing the feature about winning an
auction by bidding higher :-

    NativeException: java.lang.AssertionError:
    Tried to look for...
        exactly 1 JLabel (with name "sniper status")
        in exactly 1 JFrame (with name "Auction Sniper Main" and showing
on screen)
        in all top level windows
    and check that its label text is "winning"
    but...
        all top level windows
        contained 1 JFrame (with name "Auction Sniper Main" and showing
on screen)
        contained 1 JLabel (with name "sniper status")
        label text was "bidding"
        com/objogate/wl/PollingProber.java:38:in `check'
        com/objogate/wl/swing/driver/ComponentDriver.java:74:in `check'
        com/objogate/wl/swing/driver/ComponentDriver.java:142:in `has'
        com/objogate/wl/swing/driver/JLabelDriver.java:30:in `hasText'
        test/end-to-end/auction_sniper_driver.rb:25:in
`shows_sniper_status'
        test/end-to-end/application_runner.rb:36:in
org.jruby.exceptions.RaiseException: (SystemExit) exit
    `has_shown_sniper_is_winning'
        test/end-to-end/auction_sniper_end_to_end_test.rb:45:in
`test_0003_wins_an_auction_by_bidding_higher'