"Testing for Multiple Items - The Application Runner" in ch 16.
> The rest is similar, which means we can write a new test.
>
> Following the protocol convention, we also remember to add a new user,
> `auction-item-65432`, to the chat server to represent the new auction.
>
> The one significant change we have to make in the `ApplicationRunner` is to
> the `#start_bidding_in` method. Now it needs to accept a variable number of
> auctions passed through to the Sniper’s command line. The conversion is a
> bit messy since we have to unpack the item identifiers and append them to the
> end of the other command-line arguments — this is the best we can do with
> Java arrays.
>
> We run the test and watch it fail:

      1) Error:
    test_0004_bids_for_multiple_items(AuctionsniperSpec):
    NativeException: java.lang.AssertionError: Message
    Expected: is not null
         but: was null

Notes:

* Using the Ruby splat operator and `Array#map` I've avoided the need for
  the `#arguments` method mentioned in the book.
* In order to see the test fail in the way described in the book, I found that
  I needed to postpone to a later commit the change to
  `ApplicationRunner#start_bidding_in` which checks the sniper status in the UI
  for *each* auction.