"Detecting the Failure", chapter 19.
> The failure will actually occur in the `AuctionMessageTranslator` which will
> throw a runtime exception when it tries to parse the message. The Smack
> library drops exceptions thrown by `MessageHandlers`, so we have to make sure
> that our handler catches everything. As we write a unit test for a failure in
> the translator, we realize that we need to report a new type of auction
> event, so we add an `#auction_failed` method to the `AuctionEventListener`
> interface.
>
> This fails with an `ArrayIndexOutOfBoundsException` when it tries to unpack a
> name/value pair from the string. We could be precise about which exceptions
> to catch but in practice it doesn't really matter here: we either parse the
> message or we don't, so to make the test pass we extract the bulk of
> `#processMessage` into a `#translate` method and wrap a try/catch block
> around it.
>
> While we're here, there's another failure mode we'd like to check. It's
> possible that a message is well-formed but incomplete. It might be missing
> one of its fields such as the event type or current price. We write a couple
> of tests to confirm that we can catch these.
>
> Our fix is to throw an exception whenever we try to get a value that has not
> been set, and we define `MissingValueException` for this purpose.

Notes:

* The "bad message" used in the first unit test results in a `NoMethodError`
  exception (with message: "undefined method `strip' for nil:NilClass") in the
  Ruby version, but I've chosen to rescue all standard errors so this is moot.
* `Hash#fetch` raises an `IndexError` with a message: "key not found", so
  I didn't bother with the `MissingValueException`.